name: CI devops 2025

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Build and test with Maven
        run: mvn clean verify --file ./simple-api/pom.xml

      - name: Run SonarCloud analysis
        run: mvn -B verify sonar:sonar \
          -Dsonar.projectKey=buhsnn_tp-devops-correction-docker \
          -Dsonar.organization=bdml-efrei \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          --file ./simple-api/pom.xml

          